import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import AuthProvider from "./AuthProvider";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={sora.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
